
interface HeaderConfig {
    id: String,
    name: String,
    description: String
}

export const headerConfigData: HeaderConfig[] = [
  { "id": "1", name: "All", "description": "Show all AI generated images" },
  { "id": "2", "name": "Humans", "description": "Portraits and people generated by AI" },
  { "id": "3", "name": "Nature", "description": "Landscapes, forests, mountains, oceans" },
  { "id": "4", "name": "Creatures", "description": "Mythical beings, dragons, fantasy characters" },
  { "id": "5", "name": "Animals", "description": "Wildlife, birds, aquatic life" },
  { "id": "6", "name": "Environment", "description": "Sky, weather, underwater, deserts" },
  { "id": "7", "name": "Cities", "description": "Urban views, futuristic architecture, skylines" },
  { "id": "8", "name": "Fantasy", "description": "Magical worlds, surreal and fantasy art" },
  { "id": "9", "name": "Sci-Fi", "description": "Space, planets, cyberpunk, steampunk" },
  { "id": "10" , "name": "Abstract", "description": "Surreal, dreamscapes, modern abstract art" },
  { "id": "11" , "name": "Technology", "description": "Robots, gadgets, AI machines, vehicles" },
  { "id": "12" , "name": "Architecture", "description": "Castles, temples, interiors, futuristic buildings" },
  { "id": "13" , "name": "Lifestyle", "description": "Food, drinks, sports, culture, traditions" },
  { "id": "14" , "name": "Art Styles", "description": "Anime, cartoon, oil painting, 3D renders" }
]